import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/components/theme-provider";
import TokenProvider from "@/components/token-provider";
import BreadCrumbs from "@/components/shared/BreadCrumbs";
import { after } from "node:test";
import Providers from "@/components/context/shared/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  after(() => {
    console.log("root layout rendered");
  });
  return (
    <html lang="en">
      <TokenProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <BreadCrumbs />
          <Providers>{children}</Providers>
        </body>
      </TokenProvider>
    </html>
  );
}
